name: deploy-opentofu

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "opentofu/**"
  pull_request:
    paths:
      - "opentofu/**"

jobs:
  opentofu:
    name: opentofu
    runs-on: ubuntu-latest
    permissions:
      contents: write # This is required for actions/checkout
      id-token: write # This is required for requesting the JWT
      pull-requests: write
    environment: main
    env:
      # Setting an environment variable with the value of a configuration variable determined by environment
      account_name: ${{ vars.ACCT_NAME }}
      account_number: ${{ vars.ACCT_NUM }}
      working_directory: "opentofu/"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Extract branch name
        shell: bash
        run: echo "branch=$(echo "${GITHUB_REF#refs/heads/}")" >> "$GITHUB_OUTPUT"
        id: extract_branch
      - uses: dorny/paths-filter@v3
        name: Filter for changes
        id: changes
        with:
          base: ${{ steps.extract_branch.outputs.branch }}
          filters: |
            opentofu:
              - 'opentofu/**'
      - name: OpenTofu Action
        if: ${{ steps.changes.outputs.opentofu == 'true' }}
        uses: ./.github/actions/opentofu
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          EVENT_NAME: ${{ github.event_name }}
          ACTOR: ${{ github.actor }}
          REF: ${{ github.ref }}
          ACCT_NUM: ${{ env.account_number }}
          ACCT_NAME: ${{ env.account_name }}
          WORK_DIR: ${{ env.working_directory }}